require 'msgpack_rails/3/renderer'
require 'msgpack_rails/3/activeresource_formats/msgpack_format'
require 'msgpack_rails/3/serialization/activemodel_serializer'
require 'msgpack_rails/3/serialization/external_libs'
require 'msgpack_rails/3/middleware/messagepack_parser'